### ISSUE TITLE
Useful resources for learning kanji

### ISSUE THREAD

**Issue by xfq** [yudataguy/Awesome-Japanese#24]
There are two very useful resources for learning kanji (and I use them almost every day). I think they can be added into the [kanji](https://github.com/yudataguy/Awesome-Japanese#kanji) section (I can send a PR if needed):

## Kanjipedia

https://www.kanjipedia.jp/

It is a kanji search site operated by the [Japan Kanji Aptitude Testing Foundation](https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E6%BC%A2%E5%AD%97%E8%83%BD%E5%8A%9B%E6%A4%9C%E5%AE%9A%E5%8D%94%E4%BC%9A). It is possible to [find kanji by their parts](https://www.kanjipedia.jp/sakuin/bushu/1), which is very useful when I see a kanji I don’t recognize.

## Kakijun

https://kakijun.jp/

You can find the stroke order of a kanji by copying the kanji you want to check into the box in the upper left corner, and click "検索". Scroll down to see the number of strokes, radicals, pronunciation (On’Yomi and Kun’Yomi) and other information.

**Comment by yudataguy** [comment]
awesome find! would you like to contribute to the list directly?

**Comment by xfq** [comment]
See https://github.com/yudataguy/Awesome-Japanese/pull/25
