### ISSUE TITLE
All Japanese All The Time (Overview/Timeline)  Video on YouTube not available.

### ISSUE THREAD

**Issue by idleboy4038** [yudataguy/Awesome-Japanese#42]
[All Japanese All The Time (Overview/Timeline)](https://www.youtube.com/watch?v=9PdPOxiWWuU) - For people willing to completely immerse themselves in Japanese.

This video is no more avaliable.

**Comment by yudataguy** [comment]
thanks for the update, will remove it next

**Comment by idleboy4038** [comment]
> thanks for the update, will remove it next

your welcome.
